### ISSUE TITLE
Docs v. difficult to read due to poor contrast

### ISSUE THREAD

**Issue by mark-summerfield** [adamsol/Pyxell#9]
I hope you offer a dark on light theme since I find the current light on dark practically unreadable. Which is a pity beause Pyxell looks interesting.

**Comment by adamsol** [comment]
The contrast of text color #E1E1E1 on background color #2C3E50 in the documentation is 8.39:1 (by https://webaim.org/resources/contrastchecker/), so I wouldn't say it's poor (far better than 4.5:1 required by WCAG). However, I understand that some people prefer dark on light, and it was supposed to switch automatically based on your system settings (https://github.com/tolking/vuepress-theme-default-prefers-color-scheme), but there was a problem with completely illegible code snippets in the light theme. This is of course something that needs to be fixed. Ideally, there should be a manual switch, as not everyone knows about the system color settings.

**Comment by adamsol** [comment]
I have added light mode and a switch in the docs. Unfortunately, code snippets remain dark, as it's the default in Vuepress and it's difficult to change. See https://github.com/vuejs/vuepress/issues/1401 and https://github.com/PrismJS/prism/issues/807.

**Comment by mark-summerfield** [comment]
Thank you so much, the Light mode works great!
Now I can read your docs:-)
